### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by ranchop** [biswaroopmukherjee/bec1db#1]
-- Be able to import bec1db when servers are not connected. There is an error when its not able to connect to the server to refresh the database. 

-- A setting that determines the allowable time offset between image name and snippet entry.

**Comment by bec1** [comment]
Making image_query function more versatile. Depending on different types of inputs (imagesin, paramsin), have different types of outputs. 

- For string and string, output a number
- When only the imagename is provided, output a dataframe of all the parameters
- For string imagename and a list of paramsin, output pandas dataframe
- For a list of imagename and paramsin, output the pandas dataframe

I can't decide if pandas dataframe, pandas series or good'ol dict is better for various scenarios.

**Comment by biswaroopmukherjee** [comment]
The features from the first comment are now online! I moved the other features to a new issue.
