### ISSUE TITLE
Appropriate Error Message when Cicero Entry is Missing

### ISSUE THREAD

**Issue by bec1** [biswaroopmukherjee/bec1db#3]
The following error happens when one of the imagename in the list has no matching entry in the Snippet filefor (this happened because cicero had crashed). It would be nice if there was an error message with this information provided.  [Now Julian is typing] In Julian's matlab regexp this results in an error message and writes NaN. Pretty hot! Maybe we should use it again. [Parth is now typing again] You sucks!

The python line
`_ = bec1db.image_query(df.name.tolist(), ['ImagFreq1'])
`

Error Traceback
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-422-f632dffd276b> in <module>()
      3 # Get Cicero Parameters
      4 bec1db.refresh()
----> 5 _ = bec1db.image_query(df.name.tolist(), ['ImagFreq1'])
      6 df['freq'] = _.ImagFreq1
      7 df.head()

q:\roop\dataapi\dataapi\bec1db\dbreader.py in image_query(self, imagesin, paramsin)
    300             df = df.append(pd.DataFrame(results,columns=paramsin), ignore_index=True)
    301 
--> 302         df['imagename'] = imagesin
    303 
    304         return df

C:\Anaconda3\lib\site-packages\pandas\core\frame.py in __setitem__(self, key, value)
   2417         else:
   2418             # set column
-> 2419             self._set_item(key, value)
   2420 
   2421     def _setitem_slice(self, key, value):

C:\Anaconda3\lib\site-packages\pandas\core\frame.py in _set_item(self, key, value)
   2483 
   2484         self._ensure_valid_index(value)
-> 2485         value = self._sanitize_column(key, value)
   2486         NDFrame._set_item(self, key, value)
   2487 

C:\Anaconda3\lib\site-packages\pandas\core\frame.py in _sanitize_column(self, key, value, broadcast)
   2654 
   2655             # turn me into an ndarray
-> 2656             value = _sanitize_index(value, self.index, copy=False)
   2657             if not isinstance(value, (np.ndarray, Index)):
   2658                 if isinstance(value, list) and len(value) > 0:

C:\Anaconda3\lib\site-packages\pandas\core\series.py in _sanitize_index(data, index, copy)
   2798 
   2799     if len(data) != len(index):
-> 2800         raise ValueError('Length of values does not match length of ' 'index')
   2801 
   2802     if isinstance(data, PeriodIndex):

ValueError: Length of values does not match length of index

**Comment by biswaroopmukherjee** [comment]
Done!
