### ISSUE TITLE
Speed Improvements

### ISSUE THREAD

**Issue by bec1** [biswaroopmukherjee/bec1db#5]
It takes a few seconds to find 50 images! We need to find places where speed can be improved.

- What step is taking the longest time? Use line_profiler to find out. 
- Is it faster to get all parameters for a particular imagename from the database rather than find select few that are asked?
- Is it faster to first get a list of all rows for the provided list of imagenames, and then access them one by one? Or is it faster to ask the database to give all imagenames at once?
- Would it be better to have another database which has only two columns, one for imagetime and other for row number (one for the entire database)

**Comment by biswaroopmukherjee** [comment]
Now takes 0.5s for 230 images.
